# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4484f3ddfc24529c28d6bcff149a9f32e1659ff2e3c00b5b8955b077a660123ac36547b29132afa8c5ab934f687c124c27996f8afb21ed280ee92bacc8cd66aa

test:
  secret_key_base: 265d830b754d354f34b2e070c122f9b90243d6f00bb6e883cad7c2cd2998a1e3866e1fb43056651dd67280b0274721520c2256cb9ff4d91030ba2f9d4f56950f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
